name: Test SSH Connection
on: [workflow_dispatch]

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Check
        uses: appleboy/ssh-action@v0.1.10
        with:
          debug: true
          host: njs.bellox.eu
          username: ${{ secrets.PROXMOX_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Erfolgreich verbunden!"
            uname -a
            docker --version
